#
# configuration
#
server:
  port: ${port:8443}
  ssl:
    enabled: true
    key-store: event.nova-labs.org.p12
    key-store-password: novalabs
    key-password: novalabs
    key-store-type: PKCS12

https:
  protocols: "TLSv1.2,TLSv1.1"


spring:
  # data source for persisting data
  datasource:
    url: jdbc:h2:file:./h2db/eventdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  # enable H2 web console and set url for web console
  # http://localhost:8080/console
  h2:
    console:
      enabled: true
      path: /console

  # Spring Security
  security:
    basic:
      enabled: false

  # endpoint config
  endpoints:
    enabled: true
    actuator:
      enabled: true
      sensitive: false
    env:
      enabled: true
      sensitive: false
